# Generated by Django 5.0.4 on 2024-04-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('id_duffle', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id_category'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('id_duffle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['id_warehouse'],
            },
        ),
        migrations.CreateModel(
            name='MyDuffle',
            fields=[
                ('id_duffle', models.AutoField(primary_key=True, serialize=False)),
                ('name_duffle', models.CharField(max_length=20, verbose_name='Наименование')),
                ('heft', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Вес')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ready_app.category')),
                ('warehouse', models.ManyToManyField(default=1, to='ready_app.warehouse')),
            ],
            options={
                'verbose_name': 'Снаряжение',
                'verbose_name_plural': 'Снаряжение',
                'ordering': ['id_duffle'],
            },
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_duffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ready_app.myduffle', verbose_name='Поход')),
            ],
        ),
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_duffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ready_app.myduffle', verbose_name='БП')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_duffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ready_app.myduffle', verbose_name='Велосипед')),
            ],
        ),
        migrations.CreateModel(
            name='WaterRafting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_duffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ready_app.myduffle', verbose_name='Сплав')),
            ],
        ),
    ]
