# Generated by Django 5.0.4 on 2024-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_duffle',
            new_name='name_duffle',
        ),
    ]
