# Generated by Django 5.0.4 on 2024-04-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_app', '0002_rename_id_duffle_category_name_duffle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_duffle',
            new_name='name_category',
        ),
    ]
