# Generated by Django 5.0.4 on 2024-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_app', '0003_rename_name_duffle_category_name_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='id_duffle',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name_waterhouse',
            field=models.CharField(default='Вне склада', max_length=20, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(default='Без категории', max_length=20, verbose_name='Категория'),
        ),
    ]
